name: react-native-android-build-apk
on:
  push:
    branches:
      - main
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: cd mushroomNative && yarn install
      - name: Build Android Release
        run: cd mushroomNative/android && chmod +x ./gradlew && ./gradlew assembleRelease
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: true
          prerelease: false
          tag_name: "v1.0.0"
          release_name: "draft"
          body: "draft"
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mushroomNative/android/app/build/outputs/apk/release/app-universal-release.apk
          asset_name: app-release.apk
          asset_content_type: application/zip